### ISSUE TITLE
lxqt-session unnecessarily requires Qt > 5.5 because of qCInfo().

### ISSUE THREAD

**Issue by PCMan** [lxde/lxqt#1090]
LXQt currently only requires Qt 5.3+. Also, the stable versions of some major distros still ship Qt 5.4 at th moment. The latest lxqt-session requires Qt 5.5+ because of the use of qCInfo, which is only used in debug message only.
We should make this optional. Maybe replace it with qInfo() when qCInfo() is not available.

/home/pcman/lxqt/lxqt-session/lxqt-session/src/sessionapplication.cpp:105:31: error: ‘qCInfo’ was not declared in this scope
                 qCInfo(SESSION) << QStringLiteral("Session '%1', new input device '%2', keyboard setting will be (optionaly) reloaded...").arg(confi
                               ^
lxqt-session/CMakeFiles/lxqt-session.dir/build.make:146: recipe for target 'lxqt-session/CMakeFiles/lxqt-session.dir/src/sessionapplication.cpp.o' failed
make[2]: *** [lxqt-session/CMakeFiles/lxqt-session.dir/src/sessionapplication.cpp.o] Error 1

**Comment by PCMan** [comment]
The bug is introduced by f6fba2aa972b100f70146bc232482e5fc12394d6 .

**Comment by palinek** [comment]
Sorry, I didn't realize that the qCInfo() was introduced just recently ...
