### ISSUE TITLE
[lxqt-panel] Can't compile (Makefile error)

### ISSUE THREAD

**Issue by AlfredoRamos** [lxde/lxqt#750]
Well, as title says, I'm using the `lxqt-panel-git` package from the AUR and unfortunately I'm not able to upgrade this package in particular.

The error is not very descriptive:
```
Makefile:136: recipe for target 'all' failed
make: *** [all] Error 2
```
The full output: https://pastebin.osuosl.org/29291/
The generated Makefile: https://pastebin.osuosl.org/29301/

I tried to upgrade all my lxqt packages but it seems that I'm missing something. The `libdbusmenu-qt5` library is missing in the AUR package so I don't know if there's more missing dependencies.

The commit lxde/lxqt-panel@b710bbe was the last one I was able to compile.

I have Arch x86_64, Qt 5.5.0 (but it didn't work with 5.4.2 either), gcc 5.1.0, cmake 3.2.3

**Comment by palinek** [comment]
```
/tmp/pacaurtmp-abaddon/lxqt-panel-git/src/lxqt-panel/plugin-sysstat/lxqtsysstat.cpp:31:27: fatal error: SysStat/CpuStat: No such file or directory
```
Do you have the libsysstat-qt5 dev installed? (hm... the build should fail in the cmake phase already)

**Comment by pmattern** [comment]
There are two problems involved here:

lxqt-panel-git indeed depends on libdbusmenu-qt5 which isn't a package dependency right now.
This has been posted on the [package's page](https://aur4.archlinux.org/packages/lxqt-panel-git/) but not fixed yet.

In recent VCS versions of libsysstat a well-known old problem regarding the paths of 64-bit libraries on Arch Linux cropped up again:
It's affecting software considering [/usr]/lib64 a directory by default. Those paths are handled as symbolic links on Arch Linux but pacman refuses to install into them as such (throwing a rather misleading error message about objects existing in FHS). The workaround is to add a cmake-switch `-DCMAKE_INSTALL_LIBDIR=lib`.
This has been implemented in package libsysstat-git in AUR4 but not in AUR ("old") yet.

All LXQt components could be compiled flawlessly on Arch Linux x86_64 against Qt 5.4.2 yesterday and Qt 5.5.0 this morning here.
So all in all a downstream issue. Leaving open for now to ease further discussion if needed.

**Comment by AlfredoRamos** [comment]
Yeah, `libsysstat-git` was the problem, sorry for opening a non-related issue with lxqt-panel itself.
